### ISSUE TITLE
quand un menu est ouvert, et qu'on en ouvre un autre, il reste ouvert en dessous : fermer le menu ou les placer à des endroits différents

### ISSUE THREAD

**Issue by thyshimrod** [thyshimrod/ageofshimrod#37]
d'autant que l'affichage est dans un ordre spécifique, donc si les menus sont toujours au même endroit, ils sont superposés, et c'est le menu building qui est affiché en dernier donc par dessus les autres, quelque soit l'ordre d'ouverture

**Comment by Metilm** [comment]
tu veux n'avoir qu'un seul menu ouvert à la fois ? -> Singleton ? on peut imaginer une possibilité de glisser les menus ?

**Comment by Metilm** [comment]
je pense que ça va être lourd de placer le menu dynamiquement la ou y a de la place ^^"

**Comment by thyshimrod** [comment]
Est ce que le joueur a besoin d'avoir les différents menus ouvert à la fois?
Je serai tenté de dire que non. si effectivement, il n'a pas besoin, il suffit de fermer les autres quand on en ouvre un.
La deuxième solution, car le nb de menu n'est pas non plus extravagant, est de leur trouver une place unique dans l'écran, prédéfini.

**Comment by Metilm** [comment]
en V0 c'est certain ^^ je suis partisan du 1 menu. si le joueur il clique quelque part c'est qu'il a besoin de CE menu en plus t'as déjà bien facilité la vie, on voit les ressources assez facilement en global^^ y a peu de dépendance pour l'instant
