### ISSUE TITLE
[BUG] Villageois patine sur place pendant récolte ressource

### ISSUE THREAD

**Issue by Metilm** [thyshimrod/ageofshimrod#53]
J'ai alloué un villageois à une autre scirie, et après avoir pris une premiere fois du bois, il patine devant :'(

![image](https://user-images.githubusercontent.com/87037534/130265354-27569347-84ed-4436-82b0-5f53580f02a5.png)

**Comment by Metilm** [comment]
Reproduit sur 2 parties différentes avec ctrl maj R

**Comment by thyshimrod** [comment]
ouais ouais... 
enfin ctrl maj R, c'est juste pour rafraichir des fichiers de param en cache :D
pas tres dur, mais chiant... c'est un probleme de calcul de distance... il calcule à partir de la coordonnée en haut à droite et non du milieu du sprite... Et pour l'instant, j'ai considéré que tout faisait 32 * 32.
Je regarde ça
